spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver       #spring超过2.1就要换成cj包
    url: jdbc:mysql://localhost:3306/dorm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false       #springboot超过
    username: root
    password: root
server:
  port: 8882
  servlet:
    context-path: /dorms             #访问项目路径http://localhost:8881/dorm/
mybatis:
  mapper-locations: com/dorms/mapper/*.xml
# 打印sql到控制台
logging:
  level:
    com:
      dorms:
        mapper: debug
#配置mybatis分页,驱动是mysql
pagehelper:
  helper-dialect: mysql